[package]
name = "netstat-rust"
version = "0.1.1"
authors = ["CryShana <cryshana@cryshana.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netstat2 = "0.9.1"
sysinfo = "0.30.5"
termcolor = "1.4.1"
